# Generated by Django 3.2.9 on 2021-11-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diveapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharkfact',
            name='shark_fact_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
